/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as BantayBahaRouteImport } from './routes/bantay-baha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BantayBahaReportRouteImport } from './routes/bantay-baha.report'
import { Route as BantayBahaNearbyRouteImport } from './routes/bantay-baha.nearby'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const BantayBahaRoute = BantayBahaRouteImport.update({
  id: '/bantay-baha',
  path: '/bantay-baha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BantayBahaReportRoute = BantayBahaReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => BantayBahaRoute,
} as any)
const BantayBahaNearbyRoute = BantayBahaNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => BantayBahaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bantay-baha': typeof BantayBahaRouteWithChildren
  '/reports': typeof ReportsRoute
  '/bantay-baha/nearby': typeof BantayBahaNearbyRoute
  '/bantay-baha/report': typeof BantayBahaReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bantay-baha': typeof BantayBahaRouteWithChildren
  '/reports': typeof ReportsRoute
  '/bantay-baha/nearby': typeof BantayBahaNearbyRoute
  '/bantay-baha/report': typeof BantayBahaReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bantay-baha': typeof BantayBahaRouteWithChildren
  '/reports': typeof ReportsRoute
  '/bantay-baha/nearby': typeof BantayBahaNearbyRoute
  '/bantay-baha/report': typeof BantayBahaReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bantay-baha'
    | '/reports'
    | '/bantay-baha/nearby'
    | '/bantay-baha/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bantay-baha'
    | '/reports'
    | '/bantay-baha/nearby'
    | '/bantay-baha/report'
  id:
    | '__root__'
    | '/'
    | '/bantay-baha'
    | '/reports'
    | '/bantay-baha/nearby'
    | '/bantay-baha/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BantayBahaRoute: typeof BantayBahaRouteWithChildren
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bantay-baha': {
      id: '/bantay-baha'
      path: '/bantay-baha'
      fullPath: '/bantay-baha'
      preLoaderRoute: typeof BantayBahaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bantay-baha/report': {
      id: '/bantay-baha/report'
      path: '/report'
      fullPath: '/bantay-baha/report'
      preLoaderRoute: typeof BantayBahaReportRouteImport
      parentRoute: typeof BantayBahaRoute
    }
    '/bantay-baha/nearby': {
      id: '/bantay-baha/nearby'
      path: '/nearby'
      fullPath: '/bantay-baha/nearby'
      preLoaderRoute: typeof BantayBahaNearbyRouteImport
      parentRoute: typeof BantayBahaRoute
    }
  }
}

interface BantayBahaRouteChildren {
  BantayBahaNearbyRoute: typeof BantayBahaNearbyRoute
  BantayBahaReportRoute: typeof BantayBahaReportRoute
}

const BantayBahaRouteChildren: BantayBahaRouteChildren = {
  BantayBahaNearbyRoute: BantayBahaNearbyRoute,
  BantayBahaReportRoute: BantayBahaReportRoute,
}

const BantayBahaRouteWithChildren = BantayBahaRoute._addFileChildren(
  BantayBahaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BantayBahaRoute: BantayBahaRouteWithChildren,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
